### PR TITLE
FIX: GCC14 compatible build

### PR DESCRIPTION
**Pull request by perroboc**
Compiling using GCC14 presents some issues. Code has been updated to be compatible with GCC14, although I'm still getting some errors:

- [x] #1022

### CODE REVIEW

**Comment by perroboc** [comment]
Fixed issues on github actions pipeline

**Comment by perroboc** [comment]
Fixes #1021

**Comment by durswd** [comment]
Would you update a dependency https://github.com/effekseer/Effekseer/tree/master/Downloads and use the internal glfw?

**Comment by perroboc** [comment]
> Would you update a dependency https://github.com/effekseer/Effekseer/tree/master/Downloads and use the internal glfw?

Took me a while. Thing is linux sometimes builds libraries using lib64. I've set it so when building on linux, certain libraries look for their dependencies there (glew, glfw, libgd, libpng).

**Pull request merged**
