### PR TITLE
Kill Box/Kill Height implementation.

### PR DESCRIPTION
**Pull request by abvadabra**
This PR introduces a new dock panel called Kill Rules. It is directly inspired by Unreal Engine's [Kill Module](https://docs.unrealengine.com/4.27/en-US/RenderingAndGraphics/ParticleSystems/Reference/Modules/Kill/). 

There are two types of kill rule:
- Box - allows to kill particle when it either moves outside or inside of the defined box. Box is specified in effect's space and if checkbox `Scale And Rotation Applied` that box will follow effect's orientation and scale.
- Height - allows to kill particle when it either falls below or above defined height. Height is specified in effect's space and if checkbox `Scale And Rotation Applied` height plane will follow effect's orientation and scale.
Both options allow to fade out particle after it has been killed.

I also implented preview of both box and height plane in the edtor. 

As I wanted to keep preview rendering logic on C# side of editor I added api in EffectRenderer which allows to use LineRenderer in C# and as discussed in slack I moved grid and culling rendering to C# code.

I also incremented verson to 1704 and because of that this PR may conflict with `viewrot` branch. 

As usual, I localized new editor strings to spanish and japanese using Google Translate so you likely will want to fix them.

### CODE REVIEW

**Comment by durswd** [comment]
In my opinion,

1. 
plain with direction (+Y or -Y) is better than height because it is flexibility, it can express +X -X +Z -Z

image

2.
I think someone requires a sphere shape.
Would you add a feature?

Best regards.

**Comment by abvadabra** [comment]
>plain with direction (+Y or -Y) is better than height because it is flexibility, it can express +X -X +Z -Z

I was thinking that Height it more intuitive and familiar to UE4 users but if you think planes would be better I will do it.

>I think someone requires a sphere shape.
Would you add a feature?

Good idea, I will add it.

**Comment by abvadabra** [comment]
@durswd replaced height kill rule with plane along axis and added sphere shaped kill rule.

**Comment by MasterDrake** [comment]
is there a way to change this distance/box in the code?

**Comment by abvadabra** [comment]
> is there a way to change this distance/box in the code?

Not really, no. Effekseer's api doesn't define a general way of providing access to parameters of individual nodes, we could start from there. We also could add dynamic parameters support for kill rules values, but they're limited to just 4 floats per effect instance, so it is also not a viable option (e.g. box would need 6 dynamic parameters for full control).

May be @durswd has some other suggestions how we could implement such fine grained control from user's code?

**Comment by MasterDrake** [comment]
> > is there a way to change this distance/box in the code?
> 
> Not really, no. Effekseer's api doesn't define a general way of providing access to parameters of individual nodes, we could start from there. We also could add dynamic parameters support for kill rules values, but they're limited to just 4 floats per effect instance, so it is also not a viable option (e.g. box would need 6 dynamic parameters for full control).
> 
> May be @durswd has some other suggestions how we could implement such fine grained control from user's code?

Thank you for your quick response and sorry to bother you.
I'm really digging Effekseer but I think a more code-oriented approach is needed to take it to the next level.
Nonetheless GOOD JOB and thank you!

**Comment by abvadabra** [comment]
> > > is there a way to change this distance/box in the code?
> > 
> > 
> > Not really, no. Effekseer's api doesn't define a general way of providing access to parameters of individual nodes, we could start from there. We also could add dynamic parameters support for kill rules values, but they're limited to just 4 floats per effect instance, so it is also not a viable option (e.g. box would need 6 dynamic parameters for full control).
> > May be @durswd has some other suggestions how we could implement such fine grained control from user's code?
> 
> Thank you for your quick response and sorry to bother you. I'm really digging Effekseer but **I** think a more code-oriented approach is needed to take it to the next level. Nonetheless GOOD JOB and thank you!

I agree that better parameters access from code would be a game changer for effekseer. For example, unreal implements external parameters very well. Altough doing something similiar in effekseer would require a major overhaul, as far as I understand.

**Comment by MasterDrake** [comment]
> > > > is there a way to change this distance/box in the code?
> > > 
> > > 
> > > Not really, no. Effekseer's api doesn't define a general way of providing access to parameters of individual nodes, we could start from there. We also could add dynamic parameters support for kill rules values, but they're limited to just 4 floats per effect instance, so it is also not a viable option (e.g. box would need 6 dynamic parameters for full control).
> > > May be @durswd has some other suggestions how we could implement such fine grained control from user's code?
> > 
> > 
> > Thank you for your quick response and sorry to bother you. I'm really digging Effekseer but **I** think a more code-oriented approach is needed to take it to the next level. Nonetheless GOOD JOB and thank you!
> 
> I agree that better parameters access from code would be a game changer for effekseer. For example, unreal implements external parameters very well. Altough doing something similiar in effekseer would require a major overhaul, as far as I understand.

Yeah yeah, it's super understandable.
I do have another """"request""".
Can you please update the cmake minimum version to  3.15 or 3.22 and get rid of all the target compile directives like /w4 or /w4"100" and the old/new policies?
I can't build it in my project due to a mismatch and as far as I understand, it's no longer needed since 3.15
https://stackoverflow.com/questions/58708772/cmake-project-in-visual-studio-gives-flag-override-warnings-command-line-warnin

**Comment by abvadabra** [comment]
> > > > > is there a way to change this distance/box in the code?
> > > > 
> > > > 
> > > > Not really, no. Effekseer's api doesn't define a general way of providing access to parameters of individual nodes, we could start from there. We also could add dynamic parameters support for kill rules values, but they're limited to just 4 floats per effect instance, so it is also not a viable option (e.g. box would need 6 dynamic parameters for full control).
> > > > May be @durswd has some other suggestions how we could implement such fine grained control from user's code?
> > > 
> > > 
> > > Thank you for your quick response and sorry to bother you. I'm really digging Effekseer but **I** think a more code-oriented approach is needed to take it to the next level. Nonetheless GOOD JOB and thank you!
> > 
> > 
> > I agree that better parameters access from code would be a game changer for effekseer. For example, unreal implements external parameters very well. Altough doing something similiar in effekseer would require a major overhaul, as far as I understand.
> 
> Yeah yeah, it's super understandable. I do have another """"request""". Can you please update the cmake minimum version to 3.15 or 3.22 and get rid of all the target compile directives like /w4 or /w4"100" and the old/new policies? I can't build it in my project due to a mismatch and as far as I understand, it's no longer needed since 3.15 https://stackoverflow.com/questions/58708772/cmake-project-in-visual-studio-gives-flag-override-warnings-command-line-warnin

Regarding build process, I think it's better to write to @durswd directly via effekseer's slack: https://join.slack.com/t/effekseer/shared_invite/zt-86tcdhc6-wGGahU7VQjIPY5fqxwOTrg

**Comment by MasterDrake** [comment]
> > > > > > is there a way to change this distance/box in the code?
> > > > > 
> > > > > 
> > > > > Not really, no. Effekseer's api doesn't define a general way of providing access to parameters of individual nodes, we could start from there. We also could add dynamic parameters support for kill rules values, but they're limited to just 4 floats per effect instance, so it is also not a viable option (e.g. box would need 6 dynamic parameters for full control).
> > > > > May be @durswd has some other suggestions how we could implement such fine grained control from user's code?
> > > > 
> > > > 
> > > > Thank you for your quick response and sorry to bother you. I'm really digging Effekseer but **I** think a more code-oriented approach is needed to take it to the next level. Nonetheless GOOD JOB and thank you!
> > > 
> > > 
> > > I agree that better parameters access from code would be a game changer for effekseer. For example, unreal implements external parameters very well. Altough doing something similiar in effekseer would require a major overhaul, as far as I understand.
> > 
> > 
> > Yeah yeah, it's super understandable. I do have another """"request""". Can you please update the cmake minimum version to 3.15 or 3.22 and get rid of all the target compile directives like /w4 or /w4"100" and the old/new policies? I can't build it in my project due to a mismatch and as far as I understand, it's no longer needed since 3.15 https://stackoverflow.com/questions/58708772/cmake-project-in-visual-studio-gives-flag-override-warnings-command-line-warnin
> 
> Regarding build process, I think it's better to write to @durswd directly via effekseer's slack: https://join.slack.com/t/effekseer/shared_invite/zt-86tcdhc6-wGGahU7VQjIPY5fqxwOTrg

I tried to find durswd in that slack but with no luck. I hope he reads this :)

**Pull request merged**
