### PR TITLE
Upload Simplified Chinese translation

### PR DESCRIPTION
**Pull request by SQwatermark**
Translated from English to Chinese, also referencing Japanese.
Many Chinese characters are missing from GenShinGothic.
I used Microsoft Yahei to test. It works well but I‘'m not sure you'd want to include it.

### CODE REVIEW

**Comment by durswd** [comment]
I think that it is better to include Source Han Sans

**Comment by SQwatermark** [comment]
I tested Source Han Sans. It works in English, Japanese, Spanish, Simplified Chinese and Traditional Chinese.
I suggest to set the translation of language codes to language names to be common to all languages, as it should not be different in various languages.

**Comment by SQwatermark** [comment]
Sorry for missing Effekseer_Profiler.csv. I will upload it later.

**Comment by durswd** [comment]
Thank you!

**Pull request merged**
